// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/traffic_filter/provider.go

// Package nftables_test is a generated GoMock package.
package nftables_test

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	nftables "github.com/google/nftables"
)

// MockNFTConn is a mock of NFTConn interface.
type MockNFTConn struct {
	ctrl     *gomock.Controller
	recorder *MockNFTConnMockRecorder
}

// MockNFTConnMockRecorder is the mock recorder for MockNFTConn.
type MockNFTConnMockRecorder struct {
	mock *MockNFTConn
}

// NewMockNFTConn creates a new mock instance.
func NewMockNFTConn(ctrl *gomock.Controller) *MockNFTConn {
	mock := &MockNFTConn{ctrl: ctrl}
	mock.recorder = &MockNFTConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNFTConn) EXPECT() *MockNFTConnMockRecorder {
	return m.recorder
}

// AddRule mocks base method.
func (m *MockNFTConn) AddRule(rule *nftables.Rule) *nftables.Rule {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRule", rule)
	ret0, _ := ret[0].(*nftables.Rule)
	return ret0
}

// AddRule indicates an expected call of AddRule.
func (mr *MockNFTConnMockRecorder) AddRule(rule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRule", reflect.TypeOf((*MockNFTConn)(nil).AddRule), rule)
}

// DelRule mocks base method.
func (m *MockNFTConn) DelRule(rule *nftables.Rule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelRule", rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelRule indicates an expected call of DelRule.
func (mr *MockNFTConnMockRecorder) DelRule(rule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelRule", reflect.TypeOf((*MockNFTConn)(nil).DelRule), rule)
}

// Flush mocks base method.
func (m *MockNFTConn) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockNFTConnMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockNFTConn)(nil).Flush))
}

// GetRules mocks base method.
func (m *MockNFTConn) GetRules(table *nftables.Table, chain *nftables.Chain) ([]*nftables.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRules", table, chain)
	ret0, _ := ret[0].([]*nftables.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRules indicates an expected call of GetRules.
func (mr *MockNFTConnMockRecorder) GetRules(table, chain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRules", reflect.TypeOf((*MockNFTConn)(nil).GetRules), table, chain)
}

// ListChain mocks base method.
func (m *MockNFTConn) ListChain(table *nftables.Table, chain string) (*nftables.Chain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChain", table, chain)
	ret0, _ := ret[0].(*nftables.Chain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChain indicates an expected call of ListChain.
func (mr *MockNFTConnMockRecorder) ListChain(table, chain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChain", reflect.TypeOf((*MockNFTConn)(nil).ListChain), table, chain)
}

// ListTableOfFamily mocks base method.
func (m *MockNFTConn) ListTableOfFamily(name string, family nftables.TableFamily) (*nftables.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTableOfFamily", name, family)
	ret0, _ := ret[0].(*nftables.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTableOfFamily indicates an expected call of ListTableOfFamily.
func (mr *MockNFTConnMockRecorder) ListTableOfFamily(name, family interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTableOfFamily", reflect.TypeOf((*MockNFTConn)(nil).ListTableOfFamily), name, family)
}
