// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/traffic_filter/provider.go

// Package trafficfilter is a generated GoMock package.
package trafficfilter

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	nftables "github.com/google/nftables"
)

// MockNftConn is a mock of nftConn interface.
type MockNftConn struct {
	ctrl     *gomock.Controller
	recorder *MockNftConnMockRecorder
}

// MockNftConnMockRecorder is the mock recorder for MockNftConn.
type MockNftConnMockRecorder struct {
	mock *MockNftConn
}

// NewMockNftConn creates a new mock instance.
func NewMockNftConn(ctrl *gomock.Controller) *MockNftConn {
	mock := &MockNftConn{ctrl: ctrl}
	mock.recorder = &MockNftConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNftConn) EXPECT() *MockNftConnMockRecorder {
	return m.recorder
}

// AddRule mocks base method.
func (m *MockNftConn) AddRule(rule *nftables.Rule) *nftables.Rule {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRule", rule)
	ret0, _ := ret[0].(*nftables.Rule)
	return ret0
}

// AddRule indicates an expected call of AddRule.
func (mr *MockNftConnMockRecorder) AddRule(rule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRule", reflect.TypeOf((*MockNftConn)(nil).AddRule), rule)
}

// DelRule mocks base method.
func (m *MockNftConn) DelRule(rule *nftables.Rule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelRule", rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelRule indicates an expected call of DelRule.
func (mr *MockNftConnMockRecorder) DelRule(rule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelRule", reflect.TypeOf((*MockNftConn)(nil).DelRule), rule)
}

// Flush mocks base method.
func (m *MockNftConn) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockNftConnMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockNftConn)(nil).Flush))
}

// GetRules mocks base method.
func (m *MockNftConn) GetRules(table *nftables.Table, chain *nftables.Chain) ([]*nftables.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRules", table, chain)
	ret0, _ := ret[0].([]*nftables.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRules indicates an expected call of GetRules.
func (mr *MockNftConnMockRecorder) GetRules(table, chain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRules", reflect.TypeOf((*MockNftConn)(nil).GetRules), table, chain)
}

// ListChain mocks base method.
func (m *MockNftConn) ListChain(table *nftables.Table, chain string) (*nftables.Chain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChain", table, chain)
	ret0, _ := ret[0].(*nftables.Chain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChain indicates an expected call of ListChain.
func (mr *MockNftConnMockRecorder) ListChain(table, chain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChain", reflect.TypeOf((*MockNftConn)(nil).ListChain), table, chain)
}

// ListTableOfFamily mocks base method.
func (m *MockNftConn) ListTableOfFamily(name string, family nftables.TableFamily) (*nftables.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTableOfFamily", name, family)
	ret0, _ := ret[0].(*nftables.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTableOfFamily indicates an expected call of ListTableOfFamily.
func (mr *MockNftConnMockRecorder) ListTableOfFamily(name, family interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTableOfFamily", reflect.TypeOf((*MockNftConn)(nil).ListTableOfFamily), name, family)
}
